### ISSUE TITLE
bazel build test/alu:alu is failing

### ISSUE THREAD

**Issue by stridge-cruxml** [kkiningh/rules_verilator#10]
There is a build breakage at head with bazel 4.2.1

```
bazel build test/alu:alu
```

Gives the error:
```
ERROR: /home/$USER/rules_verilator/test/alu/BUILD:9:21: in verilator_cc_library rule //test/alu:alu:
/home/$USER/rules_verilator/verilator/defs.bzl:77:5: for 'files', got a depset of 'NoneType', expected a depset of 'File'
```

**Comment by stridge-cruxml** [comment]
As a quick work around I restored the previous method of linking:

https://github.com/CruxML/rules_verilator/tree/issue_10_work_around

**Comment by kkiningh** [comment]
It works on latest Bazel (5.2.0), so I bumped the version requirements. Let me know if it's still not working after upgrading.

**Comment by ivwumupy** [comment]
Hi,
The master branch is still not working for me (with bazel 5.2.0).
```
bazel test //...
```
gives
```
ERROR: /data/rules_verilator/verilator/internal/BUILD:4:26: no such package '@verilator_vmaster//': The repository '@verilator_vmaster' could not be resolved: Repository '@verilator_vmaster' is not defined and referenced by '//verilator/internal:toolchain_vmaster'
```
After removing `master` from `VERSION_INFO` in `verilator/internal/versions.bzl`, it gives
```
ERROR: /data/rules_verilator/test/alu/BUILD:9:21: in verilator_cc_library rule //test/alu:alu: 
for 'files', got a depset of 'NoneType', expected a depset of 'File'
```

**Comment by kkiningh** [comment]
The way to run the test for this repo is `bazel run test/alu:alu_bin`, but ideally `bazel test //...` should not return an error. I made a minor change that builds locally for me, can you please let me know if it's still not working?

**Comment by ivwumupy** [comment]
I think I've figured out (part of) the problem. When I run `bazel run test/alu:alu_bin`, in `verilator/internal/cc_actions.bzl`, the value of `linking_outputs.library_to_link` is
```
DEBUG: /data/rules_verilator/verilator/internal/cc_actions.bzl:39:10: <LibraryToLink(pic_objects=[File:[[<execution_root>]bazel-out/k8-fastbuild/bin]test/alu/_pic_objs/alu/alu], pic_static_library=File:[[<execution_root>]bazel-out/k8-fastbuild/bin]test/alu/libalu.a, dynamic_library=File:[[<execution_root>]bazel-out/k8-fastbuild/bin]_solib_k8/libtest_Salu_Slibalu.so, resolved_symlink_dynamic_library=File:[[<execution_root>]bazel-out/k8-fastbuild/bin]test/alu/libalu.so, alwayslink=false)>
```
It doesn't have a `static_library`.

**Comment by kkiningh** [comment]
What version of Bazel are you using? And what platform are you building on?

**Comment by ivwumupy** [comment]
I'm using bazel 5.2.0, on both arch and debian 11.

**Comment by ivwumupy** [comment]
> As a quick work around I restored the previous method of linking:
> 
> https://github.com/CruxML/rules_verilator/tree/issue_10_work_around

The workaround mentioned above works for me.

**Comment by kkiningh** [comment]
I think c9d360d5b3cd1750472d37b57bfce0c6fa8d98e8 should fix it, tested on Debian 11 and it passes. Can you confirm?

**Comment by ivwumupy** [comment]
It works. Thanks.
