### ISSUE TITLE
remote caching across different build environments

### ISSUE THREAD

**Issue by conjam** [kkiningh/rules_verilator#2]
hey all,

I've been looking at getting remote caching working with verilator. Verilated files are cached across build environments that are equivalent --mac to mac, linux to linux, but the problem is that a cache should be shared across build environments

``` 
ctx.actions.run(
    arguments = [args],
    executable = verilator_toolchain.verilator_executable, //problem 
    inputs = inputs,
    outputs = [verilator_output],
    progress_message = "[Verilator] Compiling {}".format(ctx.label),
)
```

After doing some digging, the only is the verilator_executable itself. Does anyone have any ideas how to eliminate the verilator_executable as an input when fetching cached files? The purist view would be that this is "non-hermetic" but I don't think that's much of an issue.

**Comment by kkiningh** [comment]
I'm not super familiar with remote caching in Bazel, but maybe you could use `ctx.actions.run_shell` and call Verilator with an absolute path on the command line? That should eliminate the dependency on the Verilator executable at least. I think there should be a way to also use a local toolchain that appears the "same" to Bazel across build environments so long as the tools are at the same absolute path, but I'm not 100% sure of that.

**Comment by kkiningh** [comment]
Would you also mind posting the execution logs for both runs (i.e. from `bazel build ... --experimental_execution_log_file=/tmp/exec1.log`)?

**Comment by conjam** [comment]
> I'm not super familiar with remote caching in Bazel, but maybe you could use `ctx.actions.run_shell` and call Verilator with an absolute path on the command line? That should eliminate the dependency on the Verilator executable at least. I think there should be a way to also use a local toolchain that appears the "same" to Bazel across build environments so long as the tools are at the same absolute path, but I'm not 100% sure of that.

This was the idea I had initially, I've had struggles learning how to call the verilator toolchain inside the bazel sandbox, I'll push to a branch in the morning to show what I was thinking there. A path to an external verilator could maybe work too, perhaps more viable.

here is the linux log: https://github.com/conjam/rules_verilator/blob/log_branch/exec_log_out/exec_linux.txt, mac log is in the same directory

**Comment by conjam** [comment]
> I'm not super familiar with remote caching in Bazel, but maybe you could use `ctx.actions.run_shell` and call Verilator with an absolute path on the command line? That should eliminate the dependency on the Verilator executable at least. I think there should be a way to also use a local toolchain that appears the "same" to Bazel across build environments so long as the tools are at the same absolute path, but I'm not 100% sure of that.

The solution was basically doing this; I tried my hardest to do it within the sandbox, but to no avail. Solution looks like: 

```python
ctx.actions.run_shell(
            arguments = [args],
            command = verilator_toolchain.verilator_executable.path + " $*",
            inputs = inputs,
            outputs = [verilator_output],
            progress_message = "[Verilator] Compiling {}".format(ctx.label),
            execution_requirements = {
                "no-sandbox": "1",
            },
        )
```

Also requires that the verilator_toolchain is pre-built (execute  `bazel build @rules_verilator//verilator:toolchain` before doing anything)
